### PR TITLE
Add guice, manage optional resources

### PR DESCRIPTION
**Pull request by ielis**
Hi Peter,
the aim of this code is to prevent null pointers resulting from situations, when the user requests certain functionality before downloading resources, such as HPO obo file.

I created a package **org.monarchinitiative.hpoworkbench.resources** with code, that handles such resources. Briefly, the resources are wrapped into JavaFX properties and listeners, which are added during controller initialization, will disable/enable all controls (button, textfield, etc) which depend on the resource upon its availability.

I also incorporated Guice into the GUI and changed a few things, mainly in the `MainController` class. I was not sure about the logic concerning the HPO annotation file parsing, please see tags **TODO(ielis)**.

I tried the code only superficially, but everything seems to work. If you like the ideas above, please check that the code makes what you expect from it.

All the best, Daniel

### CODE REVIEW

**Comment by pnrobinson** [comment]
Hi Daniel,
thanks, that seems really useful. I tried everything and it all seems to work. I will stress test a bit today and then merge.

**Comment by pnrobinson** [comment]
Hi @ielis One issue is that the annotated disease list is not being shown in the new branch (all of the diseases annotated directly or indirectly to an HPO term are shown on the HPO term page. On the disease page, just the direct annotations are shown -- this answers one TODO item also). We could maybe skype today to figure out where to implement this. Also, I would like to add some some of a message to the Webview if the resources are not initialized, that tell the user what to do.

**Comment by ielis** [comment]
Hi Peter, I could add status bar to the bottom of the BorderPane. The status bar would then show the messages to user. We could also skype today, I'm free until approx. 11 EST and I need ~5min to prepare for the call. Could you please send me message on skype or an e-mail?

**Comment by ielis** [comment]
Hi Peter, please check the newest code where status bar have been added. Also, some list of diseases corresponding is being shown for HPO term, but I am not sure that it contains correct data. Could you please check it out?

**Comment by pnrobinson** [comment]
Hi Daniel,

just check the code out, it seems to be working fine. There is one bug in the HTML switching code that is throwing exceptions (my old code) and this still needs to be fixed up, I will try to do so this evening. Then I think we are good for the next release!

thanks Peter

---

The information in this email, including attachments, may be confidential and is intended solely for the addressee(s). If you believe you received this email by mistake, please notify the sender by return email as soon as possible.

**Pull request merged**
